name: "CreateUnityPackage"
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
 
      - run: |
          mkdir ./dist
    
      - uses: natsuneko-laboratory/get-meta-from-glob@main
        with:
          includes: /*.*
          output: ./MetaList
 
      - uses: natsuneko-laboratory/create-unitypackage@main
        with:
          meta: ./MetaList
          output: dist/Test.unitypackage

      - uses: actions/upload-artifact@v4
        with:
          name: Test.unitypackage
          path: dist/Test.unitypackage