name: "CreateUnityPackage"
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
 
      - run: |
          mkdir ./dist
 
      - uses: natsuneko-laboratory/create-unitypackage@main
        with:
          root: AutoUdonSharpProgramAssetGenerator
          dest: dist/Test.unitypackage

      - uses: actions/upload-artifact@v4
        with:
          name: Test.unitypackage
          path: dist/Test.unitypackage